### ISSUE TITLE
No SQL connection possible

### ISSUE THREAD

**Issue by almereyda** [istepanov/docker-hackpad#1]
Unfortunately `docker-compose up` does not work and runs into
```
hackpad_1 | Using mysql database type.
hackpad_1 | Startup execution failed with non-200 response: 500
hackpad_1 | net.appjet.bodylock.JSRuntimeException: Error while executing: Communications link failure
hackpad_1 | 
hackpad_1 | The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
```
which resembles my other experiences at https://github.com/tom19960222/Dockerfile-hackpad/issues/1#issuecomment-137304396

`docker-compose.yml` as follows:
```
hackpad:
  image: istepanov/hackpad
  ports:
    - "9000:9000"
  environment:
    DB_PASSWORD: hackpad
  links:
    - mysql
mysql:
  image: mysql
  environment:
    MYSQL_ROOT_PASSWORD: hackpadhackpad
    MYSQL_USER: hackpad
    MYSQL_PASSWORD: hackpad
    MYSQL_DATABASE: hackpad
```

I am starting to doubt myself here.
